name: Deploy frontend to Firebase Hosting on merge

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Set environment variable for API URL
        run: echo "REACT_APP_API_URL=https://bias-audit-backend-141651492861.us-central1.run.app" > .env.production

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          CI: false # disables "treat warnings as errors"

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRAIL_LAB_DEV }}
          channelId: live
          projectId: trail-lab-dev
          entryPoint: frontend
